name: '✨ Improvement'
description: 'Submit a improvement report to help us improve'
title: '✨ Improvement: '
labels: ['improvement']
body:
  - type: markdown
    attributes:
      value: We value your time and effort to submit this improvement report. 🙏
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: '📜 Description'
      description: 'A clear and concise description of what the improvement is.'
      placeholder: "It's a improvement when ..."
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: '👟 Reproduction steps'
      description: 'How do you encountered this behaviour? Please walk us through it step by step.'
      placeholder: "1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error"
  - type: textarea
    id: expected-behavior
    attributes:
      label: '👍 Expected behavior'
      description: 'What did you think should happen?'
      placeholder: 'It should ...'
  - type: textarea
    id: additional-context
    validations:
      required: false
    attributes:
      label: '📃 Provide any additional context for the Bug.'
      description: 'Add any other context about the problem here.'
      placeholder: 'It actually ...'
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: '👀 Have you spent some time to check if this bug has been raised before?'
      options:
        - label: "I checked and didn't find similar issue"
          required: true
  - type: checkboxes
    id: read-code-of-conduct
    attributes:
      label: '🏢 Have you read the Contributing Guidelines?'
      options:
        - label: 'I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)'
          required: true
