export const AUTH_TOKEN_EXPIRATION_TIME = 30 * 24 * 60 * 60;
export const PASSWORD_HASH_SALT_ROUNDS = 10;

export const PENDING_EMAIL_VERIFICATION_USER_ID =
  'PENDING_EMAIL_VERIFICATION_USER_ID';
export const EMAIL_VERIFICATION_LINK_EXPIRATION_TIME = 24 * 60 * 60;
export const EMAIL_VERIFICATION_LINK_RESENT_TIME = 0.5 * 60;
