name: NEXT App

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i

      - name: Check formatting
        run: npm run check-format

      - name: Lint
        run: npm run check-lint

      - name: Build
        run: npm run build