name: Linting and formatting on PR
on:
  pull_request:
    branches:
      - 'main'
    
jobs:

  Continuous-Integration:

    name: Performs linting, formatting on the application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Check formatting
        run: npm run format:check